banner:
  location: classpath:static/banner.txt
        
spring:
  application:
     name: security-oauth-sso-microservice
  
logging:
  level:
    org.springframework:
      security: DEBUG

server:  
  context-path: /auth-sso-server
