banner:
  location: classpath:static/banner.txt

# Por defecto se llamara PACKAGES-MICROSERVICE 
# Spring properties
spring:
  application:
     name: packages-microservice  # Service registers under this name
     