banner:
  location: classpath:static/banner.txt

server:
  port: 8080
  
spring:
  application:
    name: zuul-edge-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://budgie.billers:8761/eureka/
  instance:
    hostname: budgie.billers
    instance-id: ${spring.application.name}:${server.port}        
  
# Todas las peticiones que lleguen con /oauth-server o /sso-server/ se derivan al endpoint del servicio cuyo indentificador se registro en eureka
zuul:   
  routes:
    oauth-server:
      sensitiveHeaders:
      path: /oauth-server/**
      service-id: SECURITY-OAUTH-MICROSERVICE      
      strip-prefix: true
    sso-server:  
      path: /sso-server/**      
      service-id: SECURITY-OAUTH-SSO-MICROSERVICE
      strip-prefix: true
  ribbon-isolation-strategy: THREAD

hystrix.command.default.execution.timeout.enabled: false          
#50 segundos
ribbon:
  ConnectTimeout:  50000
  ReadTimeout:  50000              
