banner:
  location: classpath:static/banner.txt

server:
  context-path: /budgie  
  
spring:
  application:
    name: zuul-edge-service

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:3004/auth-server/user
      
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}        
  
# Todas las peticiones que lleguen con /oauth-server o /sso-server/ se derivan al endpoint del servicio cuyo indentificador se registro en eureka
zuul:   
  routes:      
    sso-server:  
      sensitiveHeaders:
      path: /auth-server/**
      service-id: SECURITY-OAUTH-SSO-MICROSERVICE
      strip-prefix: false
    accounts:  
      sensitiveHeaders:
      path: /accounts/**
      service-id: ACCOUNTS-MICROSERVICE
      strip-prefix: false
    clients:
      sensitiveHeaders:
      path: /clients/**
      service-id: ACCOUNTS-MICROSERVICE
      strip-prefix: false
    reporter:
      sensitiveHeaders:
      path: /reporter/**
      service-id: REPORTER-MICROSERVICE
      strip-prefix: false
    packages:
      sensitiveHeaders:
      path: /packages/**
      service-id: PACKAGES-MICROSERVICE
      strip-prefix: false
    register-security:
      sensitiveHeaders:
      path: /register/**
      service-id: REGISTER-SECURITY-MICROSERVICE
      strip-prefix: false
  ribbon-isolation-strategy: THREAD

hystrix.command.default.execution.timeout.enabled: false          
#50 segundos
ribbon:
  ConnectTimeout:  50000
  ReadTimeout:  50000              
